[server]
    protocol   = "http"
    host       = "localhost"
    port       = "9000"
    sslcert    = ""
    sslprivkey = ""

[database]
    host         = "127.0.0.1"
    port         = "5433"
    user         = "medhub"
    dbname       = "clean_architecture"
    password     = "1111"
    sslmode      = "disable"

[context]
    timeout = 3000000000

[jwt]
    secret = "rDiHRMSRI_Ackzdg"
    ttl    = "10080"
