[server]
    protocol   = "http"
    host       = "localhost"
    port       = "9000"
    sslcert    = ""
    sslprivkey = ""

[database]
    host         = "127.0.0.1"
    port         = "5432"
    user         = "user"
    dbname       = "dbname"
    password     = ""
    sslmode      = "disable"

[context]
    timeout = 3000000000

[jwt]
    secret      = "secret"
    access_ttl  = "1h"
    refresh_ttl = "24h"
